object Versions {
    const val coreKtxVersion = "1.8.0"
    const val appCompatVersion = "1.4.2"
    const val materialVersion = "1.6.1"
    const val constraintLayoutVersion = "2.1.4"
    const val jUnitVersion = "4.13.2"
    const val androidTestVersion = "1.1.3"
    const val espressoVersion = "3.4.0"
    const val coilVersion = "2.1.0"
    const val interceptorVersion = "4.10.0"
    const val gsonVersion = "2.9.0"
    const val timberVersion = "5.0.1"
    const val recyclerviewVersion = "1.2.1"
    const val coroutineVersion = "1.6.3"
    const val hiltVersion = "2.38.1"
    const val retrofit2Version = "2.9.0"
    const val lottieVersion = "5.2.0"
    const val composeActivityVersion = "1.5.1"
    const val composeVersion = "1.1.1"
    const val composeViewModelVersion = "2.5.0"
    const val composeAdapterVersion = "1.1.14"
    const val composeThemeVersion = "0.16.0"
    const val glideVersion = "4.13.2"

    const val activityKTXVersion = "1.5.1"
    const val lifecycleKTXVersion = "2.6.0-alpha01"
    const val fragmentKTXVersion = "1.5.0"

    const val gradleVersion = "7.1.1"
    const val kotlinVersion = "1.6.20"
}
